### PR TITLE
Revert "Required answers-name, checks attribs"

### PR DESCRIPTION
**Pull request by SybelBlue**
Reverts ace-lab/pl-faded-parsons#53, because ~~pl-ruby-rspec-autograder~~ is not ready to handle the update. Tracking [that issue here](https://github.com/ace-lab/pl-ruby-rspec-autograders/issues/2).

Edit: the autograder in question is `saasbook/pl-rspec-autograder`, it's unclear whether that's our new unified system or not, because I don't have access to dockerhub.

### CODE REVIEW

**Comment by SybelBlue** [comment]
@nelson-lojo do you think we should revert for now? I finally understand your comment on the thread in #53.

**Comment by SybelBlue** [comment]
Note: the python autograder is perfectly happy with the new arrangement, and this merge does fix an important bug.

**Comment by SybelBlue** [comment]
## Workaround
The user can put an empty answers-name and it fools the system into working as it expects to (all answers-name references are prefixes). Is this sufficient for now? (Should we require non-empty answers-names in the future?)

**Comment by nelson-lojo** [comment]
> the autograder in question is `saasbook/pl-rspec-autograder`, it's unclear whether that's our new unified system or not, because I don't have access to dockerhub.

It is, I'll update it now and respond in this thread when it's finished

**Comment by nelson-lojo** [comment]
rspec autograder updated: https://github.com/ace-lab/pl-ruby-rspec-autograders/pull/3

**Pull request closed without merging**
