### PR TITLE
bugfix: unnecessary "unsaved changes" dialogues eliminated

### PR DESCRIPTION
**Pull request by SybelBlue**
Essentially we're going from saving once on exit to saving after every interesting interaction (key-down and drag-stop on codelines, key-down and input on blanks)

### CODE REVIEW

**Comment by SybelBlue** [comment]
Closes #44

**Comment by SybelBlue** [comment]
Some chest before merging
- [ ] check that saving after drag-stop records the new ordering
- [ ] see if cancelling submit event, saving, then submitting after a delay fixes the issue

**Comment by SybelBlue** [comment]
Issues:
- [ ] single char press, no focus lost on text box
- [ ] change trays
- [ ] just tab

**Comment by SybelBlue** [comment]
Maybe reopen soon once we figure out the fixes

**Review by nelson-lojo — APPROVED** [review]
lgtm!

Basic actions that get hooked to saves of state:
- indent/dedent in submission tray
- keydown in a blank
- release of a codeline when dragging (without indent change) (`stop` jQuery callback)

**Pull request merged**
